name: 'markitty giphy pr comment'
description: 'Add a Giphy GIF comment to new pull requests.'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  giphy-api-key:
    description: 'Giphy API Key'
    required: true

runs:
  using: 'node20'
  image: 'dist/index.js'

branding:
  icon: 'award'
  color: 'blue'
